### ISSUE TITLE
Pre 20.0.0 wheels?

### ISSUE THREAD

**Issue by Time0o** [makslevental/mlir-wheels#63]
First of all, thanks for creating this, super handy for manylinux builds. But I noticed that the release only seems to contain builds for LLVM/MLIR 20.0.0. Is this intentional, i.e. are wheels for previous stable versions not kept around? This would be quite handy because when building an MLIR project in manylinux, while releases can just be downloaded from the LLVM website, those don't contain MLIR Python bindings which is a bit of pain. If I wanted to build and release wheels for previous versions myself, what would I have to adapt here?

**Comment by makslevental** [comment]
Yea only -30 days builds are kept (like previous 30 days). The reason is, obv, that keeping around all builds would lead to enormous storage requirements (which I'm already pushing the limits of but MS has never complained...).

> If I wanted to build and release wheels for previous versions myself, what would I have to adapt here?

The repo is already setup to build a particular commit: since `Distro` is a `workflow_dispatch` job I have this dropdown under `Run workflow`:

![Screenshot from 2024-12-10 09-37-34](https://github.com/user-attachments/assets/4c900180-1446-47ce-bb93-5a03fe010612)

So I can build whatever commit for you but it'll still be gone within 30 days. If you fork the repo you should be able to just set things up yourself and then disable the `Cleanup old releases` [workflow](https://github.com/makslevental/mlir-wheels/blob/main/.github/workflows/clean_releases.yml) and you'll have all the wheels forever. But like I said, in its current config, you're gonna start blowing up storage quickly.

**Comment by TimoNicolai-synthara** [comment]
@makslevental Thanks, I actually only need a few particular releases so I will try out what you suggested and that should work for me.

**Comment by Time0o** [comment]
@makslevental Thanks, I actually only need a few particular releases so what you suggested should work for me.
